/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CardData } from "../typing/index.d";
export { CardData } from "../typing/index.d";
export namespace Components {
    interface KitBox {
        "add": (data: CardData) => Promise<void>;
        "createPoster": () => Promise<HTMLCanvasElement>;
        "getDomList": () => Promise<CardData[]>;
        "height": number;
        "init": (list?: CardData[]) => Promise<void>;
        "updateCurrentData": (data: CardData) => Promise<void>;
        "width": number;
    }
    interface KitCard {
        "data": CardData;
        /**
          * @default 1
         */
        "zoom": number;
    }
    interface KitMove {
        "data": CardData;
        /**
          * @default 1
         */
        "zoom": number;
    }
    interface KitShortcut {
        "data": CardData;
        /**
          * @default 0
         */
        "moveY": number;
    }
    interface KitSvg {
        "data": CardData;
    }
}
export interface KitBoxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKitBoxElement;
}
export interface KitMoveCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKitMoveElement;
}
export interface KitShortcutCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKitShortcutElement;
}
declare global {
    interface HTMLKitBoxElementEventMap {
        "currentDataChange": CardData;
    }
    interface HTMLKitBoxElement extends Components.KitBox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLKitBoxElementEventMap>(type: K, listener: (this: HTMLKitBoxElement, ev: KitBoxCustomEvent<HTMLKitBoxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLKitBoxElementEventMap>(type: K, listener: (this: HTMLKitBoxElement, ev: KitBoxCustomEvent<HTMLKitBoxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLKitBoxElement: {
        prototype: HTMLKitBoxElement;
        new (): HTMLKitBoxElement;
    };
    interface HTMLKitCardElement extends Components.KitCard, HTMLStencilElement {
    }
    var HTMLKitCardElement: {
        prototype: HTMLKitCardElement;
        new (): HTMLKitCardElement;
    };
    interface HTMLKitMoveElementEventMap {
        "dataChanged": CardData;
        "toUp": CardData;
        "toDown": CardData;
        "toDelete": CardData;
    }
    interface HTMLKitMoveElement extends Components.KitMove, HTMLStencilElement {
        addEventListener<K extends keyof HTMLKitMoveElementEventMap>(type: K, listener: (this: HTMLKitMoveElement, ev: KitMoveCustomEvent<HTMLKitMoveElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLKitMoveElementEventMap>(type: K, listener: (this: HTMLKitMoveElement, ev: KitMoveCustomEvent<HTMLKitMoveElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLKitMoveElement: {
        prototype: HTMLKitMoveElement;
        new (): HTMLKitMoveElement;
    };
    interface HTMLKitShortcutElementEventMap {
        "toUp": CardData;
        "toDown": CardData;
        "toDelete": CardData;
    }
    interface HTMLKitShortcutElement extends Components.KitShortcut, HTMLStencilElement {
        addEventListener<K extends keyof HTMLKitShortcutElementEventMap>(type: K, listener: (this: HTMLKitShortcutElement, ev: KitShortcutCustomEvent<HTMLKitShortcutElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLKitShortcutElementEventMap>(type: K, listener: (this: HTMLKitShortcutElement, ev: KitShortcutCustomEvent<HTMLKitShortcutElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLKitShortcutElement: {
        prototype: HTMLKitShortcutElement;
        new (): HTMLKitShortcutElement;
    };
    interface HTMLKitSvgElement extends Components.KitSvg, HTMLStencilElement {
    }
    var HTMLKitSvgElement: {
        prototype: HTMLKitSvgElement;
        new (): HTMLKitSvgElement;
    };
    interface HTMLElementTagNameMap {
        "kit-box": HTMLKitBoxElement;
        "kit-card": HTMLKitCardElement;
        "kit-move": HTMLKitMoveElement;
        "kit-shortcut": HTMLKitShortcutElement;
        "kit-svg": HTMLKitSvgElement;
    }
}
declare namespace LocalJSX {
    interface KitBox {
        "height"?: number;
        "onCurrentDataChange"?: (event: KitBoxCustomEvent<CardData>) => void;
        "width"?: number;
    }
    interface KitCard {
        "data"?: CardData;
        /**
          * @default 1
         */
        "zoom"?: number;
    }
    interface KitMove {
        "data"?: CardData;
        "onDataChanged"?: (event: KitMoveCustomEvent<CardData>) => void;
        "onToDelete"?: (event: KitMoveCustomEvent<CardData>) => void;
        "onToDown"?: (event: KitMoveCustomEvent<CardData>) => void;
        "onToUp"?: (event: KitMoveCustomEvent<CardData>) => void;
        /**
          * @default 1
         */
        "zoom"?: number;
    }
    interface KitShortcut {
        "data"?: CardData;
        /**
          * @default 0
         */
        "moveY"?: number;
        "onToDelete"?: (event: KitShortcutCustomEvent<CardData>) => void;
        "onToDown"?: (event: KitShortcutCustomEvent<CardData>) => void;
        "onToUp"?: (event: KitShortcutCustomEvent<CardData>) => void;
    }
    interface KitSvg {
        "data"?: CardData;
    }
    interface IntrinsicElements {
        "kit-box": KitBox;
        "kit-card": KitCard;
        "kit-move": KitMove;
        "kit-shortcut": KitShortcut;
        "kit-svg": KitSvg;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kit-box": LocalJSX.KitBox & JSXBase.HTMLAttributes<HTMLKitBoxElement>;
            "kit-card": LocalJSX.KitCard & JSXBase.HTMLAttributes<HTMLKitCardElement>;
            "kit-move": LocalJSX.KitMove & JSXBase.HTMLAttributes<HTMLKitMoveElement>;
            "kit-shortcut": LocalJSX.KitShortcut & JSXBase.HTMLAttributes<HTMLKitShortcutElement>;
            "kit-svg": LocalJSX.KitSvg & JSXBase.HTMLAttributes<HTMLKitSvgElement>;
        }
    }
}
