/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CardData } from "../typing/index.d";
export { CardData } from "../typing/index.d";
export namespace Components {
    interface KitBox {
        "add": (data: CardData) => Promise<void>;
        "getDomList": () => Promise<CardData[]>;
        "height": number;
        "init": () => Promise<void>;
        "width": number;
    }
    interface KitCard {
        "data": CardData;
    }
    interface KitMove {
        "data": CardData;
    }
}
declare global {
    interface HTMLKitBoxElement extends Components.KitBox, HTMLStencilElement {
    }
    var HTMLKitBoxElement: {
        prototype: HTMLKitBoxElement;
        new (): HTMLKitBoxElement;
    };
    interface HTMLKitCardElement extends Components.KitCard, HTMLStencilElement {
    }
    var HTMLKitCardElement: {
        prototype: HTMLKitCardElement;
        new (): HTMLKitCardElement;
    };
    interface HTMLKitMoveElement extends Components.KitMove, HTMLStencilElement {
    }
    var HTMLKitMoveElement: {
        prototype: HTMLKitMoveElement;
        new (): HTMLKitMoveElement;
    };
    interface HTMLElementTagNameMap {
        "kit-box": HTMLKitBoxElement;
        "kit-card": HTMLKitCardElement;
        "kit-move": HTMLKitMoveElement;
    }
}
declare namespace LocalJSX {
    interface KitBox {
        "height"?: number;
        "width"?: number;
    }
    interface KitCard {
        "data"?: CardData;
    }
    interface KitMove {
        "data"?: CardData;
    }
    interface IntrinsicElements {
        "kit-box": KitBox;
        "kit-card": KitCard;
        "kit-move": KitMove;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kit-box": LocalJSX.KitBox & JSXBase.HTMLAttributes<HTMLKitBoxElement>;
            "kit-card": LocalJSX.KitCard & JSXBase.HTMLAttributes<HTMLKitCardElement>;
            "kit-move": LocalJSX.KitMove & JSXBase.HTMLAttributes<HTMLKitMoveElement>;
        }
    }
}
